version: '3.8'

services:
  postgres:
    image: ${DOCKER_IMAGE}
    container_name: ${DOCKER_CONTAINER}
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}" # Mapping ports for PostgreSQL
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent storage for PostgreSQL
      - ./data.dump:/docker-entrypoint-initdb.d/data.dump  # Optional: Initial data dump if any
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh  # Optional: Custom initialization script
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"  # Mapping ports for pgAdmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin  # Persistent storage for pgAdmin
    networks:
      - postgres-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  postgres-network:
    driver: bridge
